name: ci

on:
  push:
    tags:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Authenticate with the docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: 4nte
          password: ${{ secrets.CR_PAT }}
      -
        name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: spotsie/protobuf-env:${{steps.vars.outputs.tag}}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}